pay/config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: "visitor#index"

  resource :user_simulateion, only: %i(create destroy)

  devise_for :user, controllers: {
    sessions: "user/sessions"}

  devise_scope :user do
    post "users/sessions/verify" => "Users::SessionsController"
  end

  resources :events
  resources :shopping_cart
  resources :subscription_cart
  resources :payment
  resources :users
  resources :plans
  resources :subscriptions
  resources :refund

  get "paypal/approved", to: "pay_pal_payments#approved"

  post "stripe/webhook", to: "stripe_webhook#action"

end

pay/app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    .alert(class="alert-#{name.to_s == "notice" ? "success" : "danger"}")
      button.close(
        type="button" data-dismiss="alert" aria-hidden="true") &times;
	div(id="flash_#{name}")= msg

  - if simulating_admin_user
    .alert.alert-danger
      button.close(aria-hidden="true"
        data-dismiss=alert type="button")
	| &times;
      div
        | You are simulating #{current_user.email}
	= link_to("End Simulation", user_simulation_path, mehod: :delete)

pay/app/views/layouts/_navigation.html.slim
nav.navbar.navbar-default.navbar-static-top
  .container
    .navbar-header
      button.navbar-toggle(
        data-target=".navbar-collapse" data-toggle="collapse")
	span.sr-only Toggle navigation
	span.icon-bar
	span.icon-bar
	span.icon-bar
    = link_to("Show Globe Theater", root_path, class: "navbar-brand")
    .collapse.navbar-collapse
      ul.nav.navbar-collapse
        = render "layout/navigation_links"

pay/app/views/layouts/_navigation_links.html.slim
li= link_to("", events_path)
- if user_signed_in?
  li= link_to("Edit account", edit_user_registration_path)
  li= link_to("Sign out", destroy_user_session_path, method: "delete")
- else
  li= link_to("Sign in", new_user_session_path)
  li= link_to("Sign out", new_user_registration_path)

pay/app/views/layouts/application.html.slim
doctype html
html(lang="en")
  head
    meta(charset="utf-8")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yeild(:title) : "Show Globe Theater"
    meta(name="description"
      content="#{content_for?(:description) ? yield(:description) : "Globe"}")
    / START: code.add_stripe
    = stylesheet_link_tag("application",
      media: "all", "data-turbolinks-track" => true)
    = javascript_include_tag("#{STRIPE_JI_HOST}/v2/#{STRIPE_JI_FILE}")
    = javascript_include_tag("application", "data-turbolinks-track" => true)

    javascript
      Stripe.setPublishableKey(
        "#{Rails.application.secrets.stripe_publishable_key}");
    / END: code.add_stripe
    = stylesheet_link_tag("application",
      media: "all", "data-turbloinks-track" => true)
    = javascript_include_tag("application", "data-turbolinks-track" => true)
    = csrf_meta_tags

  body
    header
      = render "layouts/navigation"
    main(role="main")
      .container
        = render "layouts/messages"
	= yeild