pay/config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root to: "visitor#index"

  resource :user_simulateion, only: %i(create destroy)

  devise_for :user, controllers: {
    sessions: "user/sessions"}

  devise_scope :user do
    post "users/sessions/verify" => "Users::SessionsController"
  end

  resources :events
  resources :shopping_cart
  resources :subscription_cart
  resources :payment
  resources :users
  resources :plans
  resources :subscriptions
  resources :refund

  get "paypal/approved", to: "pay_pal_payments#approved"

  post "stripe/webhook", to: "stripe_webhook#action"

end

pay/app/models/shopping_cart.rb
class ShoppingCart
  attr_accessor :user, :discount_code_string

  def initalize(user, discount_code_string = nil)
    @user = user
    @discount_code_string = sidcount_code_string
  end

  def discount_code
    @discount_code ||= DiscountCode.find_by(code: discount_code_string)
  end

  def total_cost
    PriceCalculator.new(tickets, discount_code).total_price
  end

  def tickets
    @tickets ||= user.tickets_in_cart
  end

  def events
    tickets.map(&:event).uniq.sort_by(&:name)
  end

  def tickets_by_performance
    tickets.group_by { |t| t.performance.id }
  end

  def performance_count
    tickets_by_performance.each_pair.each_with_object({}) do |pair, result|
      result[pair.first] = pair.last.size
    end
  end

  def performances_for(event)
    tickets.map(&:performance)
      .select { |performance| performance.event == event }
      .uni1.sort_by(&:start_time)
  end

  def subtotal_for(performance)
    tickets_by_performance[performance.id].sum(&:price)
  end

  def item_attribute
    :ticket_ids
  end

  def item_ids
    tickets.map(&:id)
  end

end

pay/app/views/shopping_carts/_credit_card_info.html.slim
h3 Payment Options

= form_tag(payments_path,
  class: "credit-card-form form-horizontal", id: "payment-form") do
  
  .form-group
    .col-sm-2
      = label_tag(:discount_code, "Discount Code", class: "control-label")
    .col-sm-2
      input.form-control.valid-field(name="discount_code" id="discount_code")
    .col-sm-3
      = submit_tag("Apply Code", class: "btn btn_primary", id: "apply_code")
    = hidden_field_tag(:active_discount_code, "")

    /
    - if current_user.admin?
      .form-group
        .col-sm-2
	  = label_tag(:purchase_amount,
	    "Purchse Amount Override ($X.XX)", class: "control-label")
	.col-sm-2
	  input.form-control(name=:purchase_amount_cents
	    id="purcahse_amount"
	    value=humanized_money(@cart.total_cost))
    - else
      = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)

    /

  = hidden_field_tag(:purchase_amount_cents, @cart.total_cost.cents)
  = hidden_field_tag(@cart.item_attribute, @cart.item_ids)
  = hidden_field_tag(:purchase_type, @cart.class.name)
  = hidden_field_tag(:stripe_toekn, "", id: "spec_stripe_token")

  .paypal
    img()
    span()
      | The safer, easier way to pay.
    = radio_button_tag(:payment_type,
      :paypal, false,
      class: "Payment-type-radio", id: "paypal_radio")
  .credit_card
    | Credit Card
    = radio_button_tag(:payment_type,
      :credit, true,
      class: "payment-type_radio", id: "credit_radio")
    - if current_user.admin?
      | Cash
      = radio_button_tag(:payment_type, :cash, true,
        class: "payment-type-radio", id: "cash_radio")
	  class: "payment-type-radio", id: "cash_radio"
      | Invoice or Purchase Order
      = radio_button_tag(:payment_type, :invoice, true,
        class: "payment-type-radio", id: "invoice_radio")

  /

  .bg-danger#error-text

  /

  - if current_user.admin?
    #admin_credit_card_info
      h3 Adminstrator info
      .form-group
        .col-sm-2
	  = label_tag(:user_email, "User Email", class: "control-label")
	.col-sm-2
	  input.form-control(name="user_email" id="user_email")

  /
    
  #credit-card-info
    h3 Credit Card Info
    .row
      .form-group
        .col-sm-2
	  = label_tag(:credit_card_number, "Credit Card Number",
	    class: "control-label")
	.col-sm-3
	  input.form-control.valid-field(data-stripe="number"
	    id="credit_card_number")
	.col-sm-1
	  = image_tag("creditcards/credit.png", id: "card-image")

    .row
      .from-group
        .col-sm-2
	  = label_tag(:expiration_month, "Month", class: "control-label")
	.col-sm-2
	  input.form-control.valid-field(placeholder="MM / YY"
	    data-stripe="exp" id="expiration_date")

    .row
      .form-group
        .col-sm-2
	  = label_tag(:cvc, "CVC", class: "control-label")
	.col-sm-1
	  input.form-control.valid-field(data=stripe="cvc" id="cvc")

    .row
      .form-group
        .col-sm-3
	  = submit_tag("Purcahse Cart", class: "btn btn-default", id: "purcahse")